version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - python

  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]

  php:
    image: webdevops/php-nginx:8.2
    
    volumes:
      - ./php-app:/app
    ports:
      - "8003:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  python:
    image: python:3.11
    ports:
      - "8004:8000"
    volumes:
      - ./python-app:/app
    depends_on:
      - php
      - nodejs
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"