services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./frontend/build:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    
  php:
    image: webdevops/php-nginx:8.2
    
    volumes:
      - ./laravel-app:/app
    ports:
      - "8003:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  keycloak:
    image: keycloak/keycloak:24.0
    container_name: oauth-test-laravel
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]

volumes:
  mysql-data: